name: Publish to maven
on:
  push:
    tags:
      - '*'

jobs:
  test:
    - uses: actions/checkout@v3
      name: Checkout
    - uses: burrunan/gradle-cache-action@v1
      name: Cache .gradle
    - name: Test
      run: |
        ./gradlew test

  prepare:
    needs: test
    steps:
      - name: Set tags env
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

  push-internally:
    runs-on: ubuntu-latest
    needs: prepare
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Gradle publish internally
        run: | 
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain broeskamp --domain-owner 843115942280 --region eu-central-1 --query authorizationToken --output text`
          ./gradlew -Pversion=${{ env.RELEASE_VERSION }} publishMavenJavaPublicationToInternalRepository -i


  push-publicly:
    runs-on: ubuntu-latest
    needs: prepare
    env:
      OSSRH_USERNAME: ${{ OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ OSSRH_PASSWORD }}
    steps:
      - name: Install GPG secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_PGP_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Gradle publish publicly
        run: |
          ./gradlew \
            -Pversion=${{ env.RELEASE_VERSION }} \
            -Psigning.password="${{ secrets.OSSRH_GPG_SECRET_PGP_KEY_PASSWORD }}"
            publishMavenJavaPublicationToMavenCentralRepository -i